[project]
name = "fmovies-api-flask"
version = "0.1.0"
description = "Basic FMovies API for searching movies and TV shows with watch links."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4",
    "flask",
    "flask-restful",
    "gunicorn",
    "python-dotenv",
    "requests",
]
